AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]            # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False                # i am using transfer learning that's why i dont want to train my model from scratch 
EPOCHS: 2
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01